// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_Warehouse_Management_System.Data;

#nullable disable

namespace dotnet_Warehouse_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260305120042_customer_taxcode_unique_constra")]
    partial class customer_taxcode_unique_constra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Customers.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.CheckingInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("GrnItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<long>("StockUnitId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GrnItemId");

                    b.HasIndex("StockUnitId");

                    b.ToTable("CheckingInfos");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.Grn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReceivingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Grns");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.GrnItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompliantQty")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedQty")
                        .HasColumnType("int");

                    b.Property<long>("GrnId")
                        .HasColumnType("bigint");

                    b.Property<int>("NotCompliantQty")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceivedQty")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GrnId");

                    b.ToTable("GrnItems");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.StockUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long?>("SlotId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SlotId");

                    b.ToTable("StockUnits");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.Picklist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Picklists");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.PicklistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ErrorReason")
                        .HasColumnType("int");

                    b.Property<int>("PickedQty")
                        .HasColumnType("int");

                    b.Property<int>("PickingSequence")
                        .HasColumnType("int");

                    b.Property<long>("PicklistId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("SalesOrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalesOrderLineNumber")
                        .HasColumnType("int");

                    b.Property<string>("SlotCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PicklistId");

                    b.ToTable("PicklistItems");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.SalesOrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderLineNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("SalesOrderLines");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Picking.Entities.PickingInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PicklistItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StockUnitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PicklistItemId");

                    b.ToTable("PickingInfos");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Products.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Warehouses.Entities.Slot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PickingSequence")
                        .HasColumnType("int");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.CheckingInfo", b =>
                {
                    b.HasOne("dotnet_Warehouse_Management_System.GoodsIn.Entities.GrnItem", "GrnItem")
                        .WithMany("CheckingInfoList")
                        .HasForeignKey("GrnItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_Warehouse_Management_System.GoodsIn.Entities.StockUnit", "StockUnit")
                        .WithMany()
                        .HasForeignKey("StockUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrnItem");

                    b.Navigation("StockUnit");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.GrnItem", b =>
                {
                    b.HasOne("dotnet_Warehouse_Management_System.GoodsIn.Entities.Grn", "Grn")
                        .WithMany("Items")
                        .HasForeignKey("GrnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grn");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.StockUnit", b =>
                {
                    b.HasOne("dotnet_Warehouse_Management_System.Warehouses.Entities.Slot", null)
                        .WithMany("StockUnits")
                        .HasForeignKey("SlotId");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.PicklistItem", b =>
                {
                    b.HasOne("dotnet_Warehouse_Management_System.Outbound.Entities.Picklist", "Picklist")
                        .WithMany("PicklistItemList")
                        .HasForeignKey("PicklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picklist");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.SalesOrderLine", b =>
                {
                    b.HasOne("dotnet_Warehouse_Management_System.Outbound.Entities.Order", "Order")
                        .WithMany("SalesOrderLineList")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Picking.Entities.PickingInfo", b =>
                {
                    b.HasOne("dotnet_Warehouse_Management_System.Outbound.Entities.PicklistItem", "PicklistItem")
                        .WithMany("PickingInfos")
                        .HasForeignKey("PicklistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PicklistItem");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Warehouses.Entities.Slot", b =>
                {
                    b.HasOne("dotnet_Warehouse_Management_System.Products.Entities.Product", "Product")
                        .WithMany("Slots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.Grn", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.GoodsIn.Entities.GrnItem", b =>
                {
                    b.Navigation("CheckingInfoList");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.Order", b =>
                {
                    b.Navigation("SalesOrderLineList");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.Picklist", b =>
                {
                    b.Navigation("PicklistItemList");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Outbound.Entities.PicklistItem", b =>
                {
                    b.Navigation("PickingInfos");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Products.Entities.Product", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("dotnet_Warehouse_Management_System.Warehouses.Entities.Slot", b =>
                {
                    b.Navigation("StockUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
