{
 "title": "loki based dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, {app=\"wms-api\"} | json | unwrap Elapsed [$__auto]) by (RequestPath)",
     "legendFormat": "{{RequestPath}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate({app=\"wms-api\"}[1m]))"
    }
   ]
  },
  {
   "title": "Top endpoints",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(\r\n 10,\r\n sum by (RequestPath)(\r\n  count_over_time(\r\n   {app=\"wms-api\"}\r\n   | json\r\n   | SourceContext=\"Serilog.AspNetCore.RequestLoggingMiddleware\"\r\n  [5m])\r\n )\r\n)",
     "legendFormat": "{{RequestPath}}"
    }
   ]
  }
 ]
}